import Menu from './components/menu'
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-slate-950 text-white flex'>
        
        <Menu />
        {children}
      </body>
    </html>
  )
}
